language: php
php:
  - 7.2

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  sonarcloud:
    organization: "monsieurbon-github"
    token:
      secure: "vFrxlNploarCpH92BiD6woPWeNLRzYQrXttTrUtiW340sB1RaRwnAEHWTpsmFANS9AZJEyOUcwnHc1x/K0I+JTZTuMQRE+AhGYABCird38j0w5l8CuV2TDm2ViDafADPuB2AvfDQGeUHxWz8lKVEQ1vHrWMhvVqaZuBgvAtmqRIbq8r+J1ew/dtTqRWsi26GAwBDQAKAKk+BQPOykCEUsQk/PSEc/36Uu1YttHMfEQze9VlsZUHmuZzw1g/zrdAmFsF2uckEQ23jadTwlrH2uRFFMRAMpl6eQ8sbsByv3cQxPKvAlXeZQtP00ALsZd1DhNmxznuF6xPJt/O6CwtMPo5dLTbvUw1dMiYXcRgtKOH0m1GkZkOm2/OZZfLQmuZwQPVzpf5JUxhQPReYfiQrDbM8YwIgK/xX099M4Ncv/kvkRYXSmW/D8nDwGjrGtWS4eu/4zwzrc+Duxk9UGfF8iVeRsz55G8pS6N7ZlKUfBRt568/wJOpCU8qPPmV6Y9qRXYTYkTzkfeD2l/ftI1bHrITblEsDS+yWSccO1yjkNC5HxLf3oB/P/DBVEW53YivdFvvpMeuPbWYYnPqqeEd5jbVrOn1nuhOI7E+IuVVQWCgLAr86Uls+IdrK9F/mUOmVcUKKeYoC77bUsz3fEvfVUeGubUFn2Lm+CDzbhBRY3ZM="

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - yes '' | pecl install yaml
  - composer self-update

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner